### ISSUE TITLE
`showOutput` setting isn't respected anymore in VS Code 1.9 for tasks started through the extension

### ISSUE THREAD

**Issue by rotemdan** [doiyuki/Blade-Runner#2]
First, excellent extension. I've been using it for many months now and it worked very well.

Looking at the code I had no idea it would be that simple!

It seems like some change in VS Code 1.9 causes the output panel to now appear every time the task starts if the task is started through the extension, regardless if `showOutput` is set to `silent` or `never`. This didn't happen in 1.8.

I'm not exactly sure if it is a bug in VS Code or a change in the API that requires that the build task should now be started in a slightly different function call, time, or event.

I have written a bug report to VS Code but haven't submitted it yet. I want to first make sure the issue isn't related to the extension.

**Comment by rotemdan** [comment]
I opened a [VS Code issue](https://github.com/Microsoft/vscode/issues/19810) for this.

**Comment by doiyuki** [comment]
@rotemdan Thank you for you comment! I'm so glad for opening the issue on VS Code repo.

**Comment by rotemdan** [comment]
The VS Code issue has been closed and it seems to be fixed in the 1.10 release.
